### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by ProjectInfinity** [xcatliu/simplemde-theme-dark#2]
When either clicking side by side or fullscreen it doesn't fill the entire screen like it does without the theme. Instead it seems to fill out the parent.

Before clicking:
http://puu.sh/tc8XB/f09b35f2d9.png

After clicking fullscreen (same happens with side by side)
http://puu.sh/tc8Zx/3291272fdb.png

Other than that, good job! It's a million times better than not being able to see the buttons.

**Comment by xcatliu** [comment]
Looks like the `z-index` of the SimpleMDE is less than your own.

Please try to set this in your own css:

```css
.CodeMirror-fullscreen,
.editor-preview-side,
.editor-toolbar.fullscreen {
  z-index: 999;
}

.editor-preview {
  z-index: 998;
}
```

If this still can't solve your issue, please try to inspect the `z-index` of your own `div`s.
Or give me an online demo.
